#!/bin/bash

echo WHAT IS THE DEPLOYMENT VERSION?
read VERSION
echo YOUR VERSION WILL BE: $VERSION

echo RUNNING DOCKER BUILD
docker build -t <YOUR_DOCKER_BUILD_NAME>:$VERSION .
echo DOCKER BUILD FINISHED!

echo UPLOADING CONTAINER TO DOCKERHUB
docker push <YOUR_DOCKER_HUB_CONTAINER_NAME>:$VERSION
echo DOCKER UPLOAD FINISHED!

echo SSH INTO SERVER AND DEPLOY
ssh <YOUR_SERVER_USER>@<YOUR_SERVER_IP_OR_DOMAIN> "docker pull <YOUR_DOCKER_HUB_CONTAINER_NAME>:$VERSION && docker tag <YOUR_DOCKER_HUB_CONTAINER_NAME>:$VERSION <YOUR_DOKKU_APP_NAME>:$VERSION && dokku tags:deploy <YOUR_DOKKU_APP_NAME> $VERSION"
echo ALL DONE! 